### PR TITLE
Created footprint for Push switch with lcd screen in cap.

### PR DESCRIPTION
**Pull request by openelectron**
datasheet:
http://www.e3-keys.com/files/SA%20Technical%20Datasheet%20v2.1.pdf

@jkriege2 these are the footprints for the switches 
 kicad-library [pull #806](https://github.com/KiCad/kicad-library/pull/806)

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

some things I spotted immediately:
1. Please remove F.Silk from the layers of your holes and pads:
2016-11-30 07_44_58-footprinteditor keine aktive bibliothek
2. Please move the reference position (anchor) to the center of pin 1
3. add component outline on F.Fab and ensure that Silkscreen is still visible when component is mounted
4. please add couryard

Finally: Please read through the KLCs fr footprints and use our check scripts: 
  - https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
  - https://github.com/KiCad/kicad-library-utils

Best,
JAN

**Comment by openelectron** [comment]
@jkriege2  All changes as requested.

I noticed that the check scripts specify a silk screen width of 0.15mm but the KLC wiki entry (rule 6.5) says 0.12mm
I'm not sure how we get that changed...

**Comment by openelectron** [comment]
Look like that was recently changed in the KLC,

Revision 1.1, October 1st 2016
1. Specified IPC-7351C dimensions for silkscreen, courtyard and reference designator.

If you can confirm 0.12mm or 0.15mm I will correct the footprint and / or create a pull request to fix the scripts.

**Comment by openelectron** [comment]
Pretty sure its now changed to 0.12mm

I have updated and created a [pull request ](https://github.com/KiCad/kicad-library-utils/pull/69) to fix the scripts

**Comment by jkriege2** [comment]
nice work!

Could you please open a PR to connect the symbols from (https://github.com/KiCad/kicad-library/pull/806) to these footprints (i.e. set footprint field in the symbols and/or footprint filter, as fitting)? I should have kept that one open, but unfortunately didn't.
Best & thanks,
JAN

**Comment by jkriege2** [comment]
Oh, one thing is still missing (just saw): Could you move the courtyard so it has 0.25mm offset from the outline of the switch (as drawn on the F.Fab layer).

Thanks,
JAN

**Comment by openelectron** [comment]
@jkriege2  I think I have changed as requested.

Thanks

**Comment by jkriege2** [comment]
The courtyard should surround the outline (as drawn on the F.FAB-layer with an offset of 0.25mm ...

crt

**Comment by openelectron** [comment]
@jkriege2  Thanks, I misunderstood the requirements.
Rob.

**Comment by jkriege2** [comment]
One question on the pin numbering: Is it correct, that pins 1,2 are on the right and pins 3,4 on the left? That seems unusual for typical electronics components (e.g. DIP has 1-4 on the lhs and 5-8 on the rhs). I didn't find anything on that in the datasheet (actually it's not clear whether they show a bottom or top view) ... do you have one of these and can check the pin numbering?

Best,
JAN

**Comment by openelectron** [comment]
Pinout is correct. I have a switch here.

Thanks

**Comment by jkriege2** [comment]
great, thanks!

**Comment by jkriege2** [comment]
Hi!

please set width of F.FAB line to 0.1 ... otherwise it's fine!

JAN

**Comment by openelectron** [comment]
@jkriege2 
I finally got back to this. I think that should do it..

**Comment by jkriege2** [comment]
Hi!

looks good mostly. I spotted one small thing: Some pins have a F.SilkS layer. Please remove that:
2017-01-25 21_18_56-footprint editor no active library

Otherwise I will merge when it#s done!

JAN

**Comment by evanshultz** [comment]
@openelectron Will you be able to finish this PR soon?

**Comment by openelectron** [comment]
@evanshultz Sorry, This one slipped past me and I forgot to come back to it.  All done now.

**Comment by evanshultz** [comment]
@openelectron All is good. Thanks for your contribution and touch-up work here!

@jkriege2 @poeschlr Can we get a final review, if needed, and then a merge? Thanks!

**Comment by evanshultz** [comment]
@jkriege2 Can you please wrap up this PR review?

**Comment by jkriege2** [comment]
sorry for the long wait ... looks good to me now!

Thanks,
JAN

**Pull request merged**
