### PR TITLE
Added standard 6mm TACT switch

### PR DESCRIPTION
**Pull request by mpkopec**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey @mpkopec a few notes on this:
- Please expand the courtyard clearance to 0.5mm
- Please add the switch outline on the F.Fab layer  with a simple drawing, 0.15mm line thickness
- Please remove the silkscreen from each of the pads (select pad options and de-select the F.SilkS layer)
- Renumber pads as 1/1 and 2/2 to match the other similar buttons in the library

e.g.

button

Thanks :)

**Comment by mpkopec** [comment]
I've implemented all of the suggestions, thanks for the help! When it comes to F.Fab, as I didn't find any explicit demands from you or KLC I've made it exactly the body outline which is a square 6x6mm. If it should be changed just let me know :)

**Comment by SchrodingersGat** [comment]
Thanks, great work :)

Regarding the fabrication outline, the KLC needs to be updated to reflect this (new) requirement. We're working on it, thanks for making it happen :)

**Comment by mpkopec** [comment]
Great! As I don't know where to post it, I have registered a blueprint for refreshing schematic libs in KiCad launchpad, also I talked to two of the developers in person and they told it's completely possible to have it without waiting forever, let's hope that it will be added soon :)

**Pull request merged**
