### PR TITLE
Add tactile switch SKHH right angle 

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

have a set of rules (KLC) that parts for this lib need to conform to. You can find them here:
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
We are currently also discussiong an extended version with more explanations: https://github.com/SchrodingersGat/kicad-library/wiki/KLC + Discussion about this: https://github.com/KiCad/kicad-library/issues/879

There's also a set of Python scripts that can check some of these rules automatically and even fix some problems: https://github.com/KiCad/kicad-library-utils

Now about your components: 
1. Please add a courtyard (F.CrtYd with=0.05mm) line that surrounds the component
2. Please move the silkscreen, so it is not directly below the component, see e.g.:
2016-12-04 22_59_49-footprinteditor keine aktive bibliothek
3. The reference label should be on F.SilkS

Best,
JAN

**Comment by svheymann** [comment]
Done. I see, i will have to get that footprint checker...

**Comment by jkriege2** [comment]
Courtyard als Silkscreen seem fine, but an outline of the scwitch package itself (seen from above) is still missing on the F.Fab layer (width: 0.1mm)!

Best,
JAN

**Comment by svheymann** [comment]
Hmm, but i can see it in my view and i am quite convinced it is all checked in?
Here is a screenshot of what i see:
tactsw

**Comment by jkriege2** [comment]
Hhmmm ... then I've overseen it somehow. Thanks for the nice work!

JAN

**Pull request merged**
