### PR TITLE
Added a Footprint for the Omron-B3F through hole switch

### PR DESCRIPTION
**Pull request by McSpeck**
Added Omron-B3F Footprint. Already used in a pcb design.

Please check if it's ok.

Regards from Germany
McSpeck

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Please make it compliant with the KiCad Library Convention.

Thanks!

**Comment by McSpeck** [comment]
Hi CarlPoirier,

I now used the new Design Rules. 
Please have a quick view if its ok this way.
- Added a Courtyard-shape
- relocated the pins so that Pin1 is in de upper left corner
- placed the anchor on pin 1
- renamed the file according to the rules (hopefully :D) to "SW_TH_Tactile_Omron_BF3.kicad_mod" 
- marked pin 1 in the silk screen

damn i forgot nearly everything :D

Thanks.

**Comment by odurc** [comment]
Hello @McSpeck. It's ok now, the only suggestion I do is to also include which B3F series is the footprint. For example: 3BF-1xxx.
Thank you.

**Comment by McSpeck** [comment]
hi  @ricardocrudo ,
i changed the filename from SW_TH_Tactile_Omron_BF3 to SW_TH_Tactile_Omron_B3F-10xx. 
(BF3 was wrong anyway :D, its B3F)

And i added your suggestion to use B3F-10xx to specify the series.  

Regards.

**Comment by CarlPoirier** [comment]
Hi @McSpeck,

Thanks for your contribution!

**Pull request merged**
