### PR TITLE
adding Tactile_SPST_Angled

### PR DESCRIPTION
**Pull request by odurc**

### CODE REVIEW

**Comment by michal777** [comment]
Silkscreen overlaps pads.
Courtyard overlaps pads - should be 0.25 mm from pads.
Bad link to 3d.
Why pads are NPTH?

**Comment by odurc** [comment]
> Why pads are NPTH?

The two pads that are NPTH are from frame that holds the button.
The footprint is based on this part: http://www.te.com/catalog/products/en?q=1825027-2
I'm adding its part number to description and keywords

**Comment by michal777** [comment]
I don't know when NPTH in kicad should be used but AFAIK plated holes are better (it's harder to destroy them).

**Comment by michal777** [comment]
Merged. Thanks.

**Pull request merged**
