### PR TITLE
Dip switches added

### PR DESCRIPTION
**Pull request by kajusK**
Packages for KiCad/kicad-library#106, the 3d packages pull request will follow.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Jakub,

The same comments I told you on your other pull request apply here.

For the slide switches, to indicate pin one using the silkscreen and still have the mark visible after assembly and without going outside the courtyard, I suggest something like this:

(module a:SW_DIP_x2_Slide (layer F.Cu) (tedit 54C307F5)
  (descr http://www.ctscorp.com/components/Datasheets/206-208.pdf)
  (clearance 0.25)
  (fp_text reference SW_DIP_x2_Slide (at 0.025 -6.69) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value VAL*\* (at 0.775 6.56) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -4.025 -5.34) (end -4.025 5.36) (layer F.CrtYd) (width 0.05))
  (fp_line (start -4.025 5.36) (end 4.125 5.36) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.125 5.36) (end 4.125 -5.34) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.125 -5.34) (end -4.025 -5.34) (layer F.CrtYd) (width 0.05))
  (fp_line (start -3.705 5.02) (end -3.705 -2.03) (layer F.SilkS) (width 0.15))
  (fp_line (start -1.225 -5.02) (end 1.315 -5.02) (layer F.SilkS) (width 0.15))
  (fp_line (start 3.795 -2.03) (end 3.795 2.03) (layer F.SilkS) (width 0.15))
  (fp_line (start -1.225 5.02) (end 1.315 5.02) (layer F.SilkS) (width 0.15))
  (pad 1 thru_hole rect (at -1.225 3.81) (size 1.524 1.824) (drill 0.762) (layers *.Cu *.Mask F.SilkS))
  (pad 4 thru_hole oval (at -1.225 -3.81) (size 1.524 1.824) (drill 0.762) (layers *.Cu *.Mask F.SilkS))
  (pad 2 thru_hole oval (at 1.315 3.81) (size 1.524 1.824) (drill 0.762) (layers *.Cu *.Mask F.SilkS))
  (pad 3 thru_hole oval (at 1.315 -3.81) (size 1.524 1.824) (drill 0.762) (layers *.Cu *.Mask F.SilkS))
  (model Buttons_Switches_ThroughHole/sw_dip_2.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)

Thanks,

Carl

**Comment by kajusK** [comment]
Hi Carl,
I changed the text size and added a reference dot for Slide switches, it doesn't make the footprint much bigger. Your solution is interesting and simple but I prefer the full borders :smile:

Is that ok now?

**Comment by michal777** [comment]
Silkscreen for piano switches seems to be drawn incorrectly (wrong positions of "keys").
Courtyard should be rounded to 0.05mm (if it's problem to draw/generate new I can help with some simple tool that adds courtyard https://github.com/michal777/Footprint_Utils/tree/master/CrtYd_Gen)
Pads clearance shouldn't be set in footprint properties (libraries shouldn't be too technology dependent).
Web links can be broken in future, so it would be better to add in doc field something like: CTS Electrocomponents, Series 206/208
Names of 3d models should be the same as names of footprints (it will ease managing this stuff).
I don't like the dot for pin 1, sometimes users need to fight for every mm^2. Maybe as below?:
zrzut ekranu z 2015-01-31 02 37 00

**Comment by kajusK** [comment]
Hi Michal,
thanks for the answer, I didn't noticed shifted keys positions before, it was caused by typo in my script. You are right, the dot solution takes too much space, yours is better and looks good.

Is there anything else I should change?

**Comment by CarlPoirier** [comment]
Hi Jakub,

Sorry for the late reply. I have had a busy week. It's very great now! Thanks a lot for your contribution.

**Pull request merged**
