### PR TITLE
Added various incremental encoder footprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Alps EC11B
- Alps EC12E
- Bourns PEC11

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Datasheets:
- https://www.bourns.com/docs/product-datasheets/pec11r.pdf
- http://www.alps.com/prod/info/E/PDF/Switch/Encoder/EC12E/EC12E.PDF
- http://www.alps.com/prod/info/E/PDF/Switch/Encoder/EC11/EC11.PDF

**Review by pointhi — CHANGES_REQUESTED** [review]
```
checking module: Encoder_Alps_EC11B15202AA
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Encoder_Alps_EC11B15242AE_Pushbutton
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Encoder_Alps_EC11B15242AF_Pushbutton
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Encoder_Alps_EC12E
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Encoder_Bourns_PEC11-N
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
checking module: Encoder_Bourns_PEC11-S_Pushbutton
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
```

I know it's a bit idiotic for such parts, but we either need to follow it or change it.
- Remove the Silk Screen from the NTPH Holes

**Comment by evanshultz** [comment]
@SchrodingersGat Will you be able to finish this PR soon?

**Comment by SchrodingersGat** [comment]
@evanshultz thanks for the reminder. I have fixed KLC errors

**Comment by evanshultz** [comment]
@SchrodingersGat 
Thanks! I decided to start trying to resolve open items one way or another yesterday. I appreciate your help to get back on this PR.

@pointhi @jkriege2 @poeschlr 
Could we please get a review and merge if all issues are addressed?

**Comment by evanshultz** [comment]
@SchrodingersGat 
Finally getting around to reviewing other outstanding PRs. Sorry if this is pedantic, but I haven't merged anything yet so I'm trying to be thorough and I know you appreciate good effort.

Encoder_Alps_EC11B15202AA
1. The outer mtg holes aren't plated. I think they should be plated and with an annular ring for stability. Also, I've seen ESD from touching the pot enter the board and cause havoc, which could possibly be avoided by conducting the encoder body (though those mtg holes) to ground by a spark gap.
1. Outer mtg holes are 2x2.2mm oval while datasheet says 1.8x2.1mm square. Does this pad work?
1. It's hard to make out in the drawing, but it appears from the mounting surface there are two dimensions to the holes: 3.7mm and 3.8mm. I'm wondering if the A/B/C pins should be 0.1mm from the mtg holes? I can't find other Alps drawings online to confirm.
1. I calculate the mtg hole centers should be 11.7mm apart (13.5mm - 1.8mm). Your mtg hole pads are 13.5mm apart.
1. Are the F.Fab lines coming off the side of the pot showing the mounting surface? Is there a better way to show this that won't clog up the F.Fab layer? Dwgs.User?
1. Courtyard line at the back of the part is more than 0.5mm away.
1. Some courtyard lines are not on a 0.1mm grid.

Encoder_Alps_EC11B15242AE_Pushbutton
1. Some items are the same as above.
1. The mounting surface here is at 3.75mm. If the mtg holes are in the middle of the pin rows that gives this value (5mm - 2.1mm / 2). However, the drawing also shows 3.8mm but it's unclear if this is for the first row of pins or not. Otherwise, though, I don't see what the 3.8mm dimensions is for.
1. Pins A-C are marked, so why not add D and E?

Encoder_Alps_EC11B15242AF_Pushbutton
1. Some items are the same as above.

Encoder_Alps_EC12E
1. The outer mtg holes aren't plated. I think they should be plated and with an annular ring for stability. Also, I've seen ESD from touching the pot enter the board and cause havoc, which could possibly be avoided by conducting the encoder body (though those mtg holes) to ground by a spark gap.
1. The F.Fab lines are 12.5mm apart horizontally (3.75mm + 8.75mm) while the datasheet shows 12.4mm.
1. The F.Fab lines are 13.4mm apart vertically (14.2mm - 0.8mm) while the datasheet shows 13.2mm.
1. What is the purpose of having silk around the inner circle since it will be covered up? Just cosmetic?
1. The outer mtg holes aren't plated. I think they should be plated and with an annular ring for stability. Also, I've seen ESD from touching the pot enter the board and cause havoc, which could possibly be avoided by conducting the encoder body (though those mtg holes) to ground by a spark gap.
1. Outer mtg holes are 2.1x2.2mm oval while datasheet says 2x2.1mm square. Does this pad work?
1. I calculate the mtg hole centers should be 11.2mm apart (13.2mm - 2mm). Your mtg hole pads are 13.2mm apart.

Encoder_Bourns_PEC11-N
1. The outer mtg holes aren't plated. I think they should be plated and with an annular ring for stability. Also, I've seen ESD from touching the pot enter the board and cause havoc, which could possibly be avoided by conducting the encoder body (though those mtg holes) to ground by a spark gap.
1. I think it's best to add an `R` and rename this to `PEC11R`, since `PEC11` is an obsolete replacement for this series and `PEC11L` is physically different. And furthermore, this part is 12.5mm wide which matches only the flat shaft versions. The knurled shaft parts are 12.4mm wide. Perhaps this could be renamed to show that it's more universal, or else create two different footprints for this encoder family.
1. What is the purpose of having silk around the inner circle since it will be covered up? Just cosmetic?
1. Outer mtg holes are 2.1x2.6mm oval while datasheet says 1.8x2.6mm square. Does this pad work?
1. I calculate the mtg hole centers should be 11.4mm apart (13.2mm - 1.8mm). Your mtg hole pads are 13.2mm apart.

Encoder_Bourns_PEC11-S_Pushbutton
1. Some items are the same as above.
1. Pins A-C are marked, so why not add 1 and 2?
1. The datasheet shows the switch pins are 14.5mm above the A-C pins (7.5mm +7mm), but your footprints has them at 15mm.

**Comment by evanshultz** [comment]
Also, none of them have a 3D model reference.

**Comment by SchrodingersGat** [comment]
@SchrodingersGat we have now marked this repository as "read only" pending the transfer to the new footprint libraries at https://github.com/kicad/kicad-footprints

If you are still wanting to make this contribution, please resubmit to the new repository :)

**Pull request closed without merging**
