### PR TITLE
Add a Vertical Push Switch "SW_PUSH_x2"

### PR DESCRIPTION
**Pull request by lkundrak**
http://www.xiejia.net/UploadFiles%5C20087291121677963.pdf

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Please add the courtyard.

**Comment by lkundrak** [comment]
@CarlPoirier done. Sorry for the delay.

**Comment by lkundrak** [comment]
Is this allright now?

**Comment by CarlPoirier** [comment]
Yes, thanks for your contribution!

**Pull request merged**
