### PR TITLE
Added: SW_PUSH_6MM_2PIN

### PR DESCRIPTION
**Pull request by BrainCoder**
For parts like:
http://www.taydaelectronics.com/tact-switch-6-6mm-5mm-through-hole-spst-no.html
and
http://makerspot.com/6mm-2pin-through-hole-tactile-switch-x-10-pack/

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@BrainCoder  do you have an appropriate datasheet for this? I'd like to check this against a correct drawing :)

**Comment by BrainCoder** [comment]
All i could find was:
http://www.wealthmetal.com/upfolder/editor/day_121025/201210251557118430.jpg

Similar switch from a different company:
http://www.khan.cn/upfile/2015061709540104104.png

**Comment by SchrodingersGat** [comment]
Alright, a few things to look at here:
1. Have a look at the KiCad Library Convention (KLC) - any footprints need to stick to this (as far as possible, there are exceptions) to be accepted. 

https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt
1.  You can use the kicad-utils scripts to check if your footprints are going to meet KLC

https://github.com/KiCad/kicad-library-utils

I ran this against the KLC script and there are the following issues:
- Movefootprint such that pin-1 is centered
- Add component outline to fabrication layer
- Expand silkscreen so it is visible when component is loaded
- Add component courtyard
- Add description text and keywords
- Remove silkscreen from pads

e.g.

sw

To help you with this and future PRs, here are some general points:
- Components need to have a 'courtyard' drawn on the F.CrtYd layer. The line width should be 0.05mm. For connectors and switches the clearance should be 0.5mm - this is all laid out in the KLC
- A simplified outline should be drawn on the F.Fab layer (this is for manufacturability)
- Silkscreen should be visible when the component is placed on the PCB (meaning it should be placed a little 'wider' than the component
- The description and text fields should be filled out

Please let me know if you need any more info about this :)

**Comment by evanshultz** [comment]
@BrainCoder Will you be able to finish this PR soon?

**Comment by BrainCoder** [comment]
I will do my best to finish it this summer vacation.

and i have no clue how to fix:
Violating Rule 10.4
    3D model reference
    No 3D model provided

**Comment by poeschlr** [comment]
In the footprint properties go to the 3d settings and fill them out.
path: ${KISYS3DMOD}/library_name.3dshapes/footprint_nam.wrl
scale: 1,1,1
offset: 0,0,0
rotation: 0,0,0

To clarify: you don't need to supply the 3d models. But the footprint should be prepared in such a way that it can be easily added.

**Comment by evanshultz** [comment]
@BrainCoder Please reply if you have further questions about resolving the outstanding issues.

**Comment by Shackmeister** [comment]
@BrainCoder Hi are you planning on fixing the remaining issue? :)

**Comment by SchrodingersGat** [comment]
@BrainCoder we have now marked this repository as "read only" pending the transfer to the new footprint libraries at https://github.com/kicad/kicad-footprints

If you are still wanting to make this contribution, please resubmit to the new repository :)

**Pull request closed without merging**
