### PR TITLE
Footprint for Wurth 430476085716 pushbutton.

### PR DESCRIPTION
**Pull request by mignon-p**
[This button](http://katalog.we-online.de/em/datasheet/430476085716.pdf) has the same footprint as the existing `SW_PUSH-12mm` footprint, except that it needs bigger holes.

wurth-button

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hi @ppelleti 
the footprint looks good but I have a few notes :)
- the silkscreen is crossing the pad clearance of 0.2mm
- the name should be "wuerth"

**Comment by mignon-p** [comment]
Thanks; I've fixed those two issues.

**Comment by Shackmeister** [comment]
the silk is still crossing, it should not be on the purple part.
to check this go to "Footprint Properties", and under "Solder Mask Clearance" set it to 0,2mm.
OBS: be sure to set it back to 0 after checking, otherwise Travis will throw an error
wuerth

**Comment by mignon-p** [comment]
When I do that, I'm seeing a different result:

wuerth-clearance

I'm using KiCad 4.0.6 on OS X 10.9.5.

**Comment by Shackmeister** [comment]
sorry my bad, didnt get the results updated probably :) 
thank you for your contribution! :D

**Pull request merged**
